services:
  database:
    image: mariadb:latest
    environment:
      MARIADB_USER: php_blog
      MARIADB_PASSWORD: php_blog
      MARIADB_ROOT_PASSWORD: php_blog
      MARIADB_DATABASE: php_blog
    networks:
      - database
  php-nginx:
    depends_on:
      - database
      - php
    build:
      context: backend
      dockerfile: nginx.dockerfile
    deploy:
      replicas: 5
    restart: unless-stopped
    expose:
      - 80-84
    networks:
      - php
      - main-nginx
  php:
    depends_on:
      - database
    build:
      context: backend
      dockerfile: php-fpm.dockerfile
    networks:
      - php
      - database
    expose:
      - 9000
  nginx:
    image: nginx:latest
    depends_on:
      -  php-nginx
    networks:
      - main-nginx
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    ports:
      - 80:80
      - 443:443   

networks:
  php:
  database:
  main-nginx: